version: '2.4'

services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
#    volumes:
#      - ${STORAGE:-/storage/docker-dev}/zookeeper/data:/bitnami/zookeeper
    hostname: zookeeper
    networks:
      - kafka
#    mem_reservation: 128m
#    mem_limit: 256m

  kafka-0:
    container_name: kafka-0
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
#    volumes:
#      - ${STORAGE:-/storage/docker-dev}/kafka/0/data:/bitnami/kafka
    depends_on:
      - zookeeper
    hostname: kafka-0
    networks:
      - kafka
      - dev
#    mem_reservation: 400m
#    mem_limit: 1024m

#  kafka-1:
#    container_name: kafka-1
#    image: docker.io/bitnami/kafka:3.1
#    ports:
#      - "9092"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_BROKER_ID=1
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - ${STORAGE:-/storage/docker-dev}/kafka/1/data:/bitnami/kafka
#    depends_on:
#      - zookeeper
#    hostname: kafka-1
#    networks:
#      - kafka
#      - dev
#    mem_reservation: 400m
#    mem_limit: 1024m
#
#  kafka-2:
#    container_name: kafka-2
#    image: docker.io/bitnami/kafka:3.1
#    ports:
#      - "9092"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_BROKER_ID=2
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - ${STORAGE:-/storage/docker-dev}/kafka/2/data:/bitnami/kafka
#    depends_on:
#      - zookeeper
#    hostname: kafka-2
#    networks:
#      - kafka
#      - dev
#    mem_reservation: 400m
#    mem_limit: 1024m

networks:
  kafka:
    name: kafka
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1
